### ISSUE TITLE
Emacs waits for the goldendict process to finish

### ISSUE THREAD

**Issue by codetrick** [stardiviner/goldendict.el#1]
If the goldendict process is not running when `goldendict-dwim` is called, emacs will launch a goldendict process and wait for it to return - which means it becomes unresponsive until goldendict is closed. While if the process is already running, it does the right thing: lookup happens in a popup window, and emacs fully responsive.

Perhaps it would be nice to check if there's no goldendict process running, and then call `call-process` with destination set to 0, so as to not hold up the emacs process.

**Comment by stardiviner** [comment]
You're right, I have goldendict added to autostart. Do you want to send pr for this problem?

**Comment by stardiviner** [comment]
Ok, I fixed it now.
